openapi: "3.1.0"
info:
  title: "Chat - OpenAPI"
  description: "SamuraiChat API"
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080
security:
  - bearerAuth: []

paths:
  /users/me/avatar:
    post:
      description: "Upload and apply new avatar. Only supports image/jpeg and image/png."
      requestBody:
        content:
          image/*: 
              schema:
                type: string
                format: binary
      responses:
        '200':
          $ref: '#/components/responses/200GenericOK'
        '400':
          $ref: '#/components/responses/400Avatar'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        
  /users/me/contacts/:username:
    post:
      description: "Add new user contact"
      parameters:
        - name: username
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UsernameType'
      responses:
        '200':
          $ref: '#/components/responses/200GenericOK'
        '400':
          $ref: '#/components/responses/400AddContact'
        '401':
          $ref: '#/components/responses/401Unauthorized'
    delete:
      description: "Remove contact"
      parameters:
        - name: username
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UsernameType'
      responses:
        '200':
          $ref: '#/components/responses/200GenericOK'


  /users/me/tokens:
    post:
      description: "Register new device token for push notifications(FCM)"
      requestBody:
        $ref: '#/components/requestBodies/TokenRegisterParams'
      responses:
        '200':
          $ref: '#/components/responses/200GenericOK'
        '400':
          $ref: '#/components/responses/400TokenRegister'
        '401':
          $ref: '#/components/responses/401Unauthorized'


  /users/username/{username}:
    get:
      description: "Get user details by username"
      parameters:
        - in: path
          name: username
          schema:
            $ref: '#/components/schemas/UsernameType'
          required: true
          description: Retrieves user using username
      responses:
        '200':
          $ref: "#/components/responses/200UserDataRetrieval"
        '400':
          $ref: '#/components/responses/400UserDataRetrieval'
        '401':
          $ref: '#/components/responses/401Unauthorized'
   
  /users/id/{uid}:
    get:
      description: "Get user details by uid"
      parameters:
        - in: path
          name: uid
          schema:
            $ref: '#/components/schemas/UidType'
          required: true
          description: UID, identifies user both in our system and underlying auth solution
      responses:
        '200':
          $ref: "#/components/responses/200UserDataRetrieval"
        '400':
          $ref: '#/components/responses/400UserDataRetrieval'
        '401':
          $ref: '#/components/responses/401Unauthorized'
  /chats:
    get:
      deprecated: false
      responses:
        '200':
          $ref: '#/components/responses/200DialogMessagesRetrieval'
        '400':
          $ref: '#/components/responses/400DialogMessagesRetrieval'
        '401':
          $ref: '#/components/responses/401Unauthorized'
  /chats/{with}:
    post:
      description: "Sends a message to user with uid <with>"
      parameters:
        - name: with
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UidType'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageData'
      responses:
        '200':
          $ref: "#/components/responses/200GenericOK"
        '400':
          $ref: '#/components/responses/400SendMessage'
        '401':
          $ref: '#/components/responses/401Unauthorized'
    get:
      description: "Retrieves a page of chat messages between auth user and user with ID {with}."
      parameters:
        - name: with
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UidType'
          description: "UID of user on another side of the chat"
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: before_timestamp
          in: query
          required: true
          description: "Request only returns messages with created_at less than <before_timestamp>"
          schema:
            $ref: '#/components/schemas/TimestampType'
        - name: inversed
          in: query
          description: "Returns messages in inversed order(i.e if true, order is from latest to oldest)"
          schema:
            $ref: '#/components/schemas/BoolType'
          
      
      responses:
        '200':
          description: "Retrieved page of chat messages('#/components/schemas/MessageArray')"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              examples:
                MessagesList:
                  value:
                    code: 0
                    msg: "Success"
                    obj: [
                      {
                        msg_id: 'AVASsvawAWD21A_unique_per_msg_id',
                        to: 'asAFwafvaeAAWfgmlk_recipient_user_id_example',
                        from: 'AdsdawfAmkegnewann_sender_user_id_example',
                        msg: 'Hello',
                        created_at: 1753294374872,
                        conv_id: 'AdsdawfAmkegnewann_sender_user_id_exampleasAFwafvaeAAWfgmlk_recipient_user_id_example' 
                      },
                      {
                        msg_id: 'dsdsaDAkdwfndak9NAKWndfwkF2akfsw',
                        to: 'AdsdawfAmkegnewann_sender_user_id_example',
                        from: 'asAFwafvaeAAWfgmlk_recipient_user_id_example',
                        msg: 'Hey:)',
                        created_at: 1753294379249,
                        conv_id: 'AdsdawfAmkegnewann_sender_user_id_exampleasAFwafvaeAAWfgmlk_recipient_user_id_example' 
                      }
                    ]
        '401':
          $ref: '#/components/responses/401Unauthorized'

    
  /register:
    post:
      security: []
      
      description: "Register new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterParams'  
      responses:
        '200':
          description: "User succesfully registered"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                code: 0
                msg: "Success"
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              examples:
                UsernameAlreadyRegistered:
                  value:
                    code: 2
                    msg: "User already exists"
                BackendError:
                  value:
                    code: 6 
                    msg: "Backend failed to create new user with <msg>"
                DBBackendError:
                  value:
                    code: 6 
                    msg: "<msg>"
          description: "Bad parameters or internal error"
          
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  examples:
    ImageTypeNotSupported:
      description: "Tried to upload image of unsupported type"
      value:
        code: 11
        msg: "Image type not supported"
    InternalError:
      description: "Any error which message starts with 'Internal. <rest of the msg>'. Is internal system error."
      value: 
        code: 11
        msg: "Internal. <rest of the msg>"
    FailedDBTokensRetrieve:
      description: "Internal failed to retrieve tokens from DB"
      value: 
        code: 11
        msg: "Failed to retrieve data from db"
    FailedDBTokensWrite:
      description: "Internal failed to persist tokens in DB"
      value: 
        code: 11
        msg: "Failed to write tokens to db with: <error>"

    FailedDBWriteMessages:
      description: "Internal failed to persist messages in DB"
      value: 
        code: 11
        msg: "Failed to write messages to db with: <details>"
    GenericOK:
      description: "Generic success response"
      value:
        code: 0
        msg: "Success"
    FailedChatsRetrieval:
      description: "Internal problem with dialogs retrieval"
      value:
        code: 11
        msg: "Failed to get chats"
    FailedValidation:
      description: "Failed validation of the request content"
      value:
        code: 11
        msg: "Failed validation: <details>"
    InvalidTargetUser:
      value:
        code: 7
        msg: "Invalid user or user is not correctly registered"
    InternalDBError:
      value:
        code: 8 
        msg: "Cant decode data from db"
    ContactNotPresent:
      value:
        code: 11
        msg: "Contact is not in the list"
    ContactAlreadyPresent:
      value:
        code: 11
        msg: "Contact is already in the list"
    DialogsList:
      value:
        code: 0
        msg: "Success"
        obj: ["conv_id1", "conv_id2", "conv_id3"]
    DialogMessagesList:
      value:
        code: 0
        msg: "Success"
        obj: [
          {
            msg_id: 'AVASsvawAWD21A_unique_per_msg_id',
            to: 'asAFwafvaeAAWfgmlk_recipient_user_id_example',
            from: 'AdsdawfAmkegnewann_sender_user_id_example',
            msg: 'Hello',
            created_at: 1753294374872,
            conv_id: 'AdsdawfAmkegnewann_sender_user_id_exampleasAFwafvaeAAWfgmlk_recipient_user_id_example' 
          },
          {
            msg_id: 'dsdsaDAkdwfndak9NAKWndfwkF2akfsw',
            to: 'AdsdawfAmkegnewann_sender_user_id_example',
            from: 'asAFwafvaeAAWfgmlk_recipient_user_id_example',
            msg: 'Hey:)',
            created_at: 1753294379249,
            conv_id: 'AdsdawfAmkegnewann_sender_user_id_exampleasAFwafvaeAAWfgmlk_recipient_user_id_example' 
          }
        ]
  responses:
# Generic
    200GenericOK:
      description: "Generic success response"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          example:
            $ref: '#/components/examples/GenericOK'
# Avatar
    400Avatar:
      description: "Failed to upload and update avatar image"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          examples:
            ImageTypeNotSupported:
              $ref: '#/components/examples/ImageTypeNotSupported'
# Contacts
    400AddContact:
      description: "Failed to add contact"
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/ApiResponse'
          examples:
            FailedValidation:
              $ref: '#/components/examples/FailedValidation'
            InternalDBError:
              $ref: '#components/examples/InternalDBError'
            InvalidTargetUser:
              $ref: '#/components/examples/InvalidTargetUser'
            ContactIsAlreadyPresent:
              $ref: '#/components/examples/ContactAlreadyPresent'
    400RemoveContact:
      description: "Failed to add contact"
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/ApiResponse'
          examples:
            FailedValidation:
              $ref: '#/components/examples/FailedValidation'
            InternalDBError:
              $ref: '#components/examples/InternalDBError'
            InvalidTargetUser:
              $ref: '#/components/examples/InvalidTargetUser'
            ContactIsNotPresent:
              $ref: '#/components/examples/ContactNotPresent'      

# Tokens
    400TokenRegister:
      description: "Failed to register token"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          examples:
            FailedVaildation:
              $ref: '#/components/examples/FailedValidation'
            FailedDBTokensRetrieval:
              $ref: '#/components/examples/FailedDBTokensRetrieve'
            FailedDBTokensWrite:
              $ref: '#/components/examples/FailedDBTokensWrite'
            

# Messages
    200DialogsListRetrieval:
      description: "Retrieved list of auth user dialogs"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          examples:
            DialogsList:
              $ref: '#/components/examples/DialogsList'
    400DialogMessagesRetrieval:
      description: "Failed to retrieve list of dialogs"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          examples:
            FailedChatsRetrieval:
              $ref: '#/components/examples/FailedChatsRetrieval'


    200DialogMessagesRetrieval:
      description: "Retrieved page of chat messages('#/components/schemas/MessageArray')"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          examples:
            MessagesList:
              $ref: '#/components/examples/DialogMessagesList'
    400SendMessage:
      description: 'Request failure'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          examples:
            InternalDBError:
              $ref: '#/components/examples/InternalDBError'
            InvalidTargetUser:
              $ref: '#/components/examples/InvalidTargetUser'
              description: 'Recipient doesnt exist'
            FailedValidation:
              $ref: '#/components/examples/FailedValidation'
            FailedDBWriteMessages:
              $ref: '#/components/examples/FailedDBWriteMessages'
#
# UserDataRetrieval
    200UserDataRetrieval:
      description: "User succesfully retrieved"
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/UserData'
    400UserDataRetrieval:
      description: "Bad Request(see examples)"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          examples:
            InvalidTargetUser:
              $ref: '#/components/examples/InvalidTargetUser'
            InternalDBError:
              $ref: '#/components/examples/InternalDBError'

# Unauthorized
    401Unauthorized:
      description: "Unauthorized"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          examples:
            UncompleteRegister:
              value:
                code: 7
                msg: "User register is incomplete, action is not authorized"
            BadHeaders:
              value:
                code: 8 
                msg: "Invalid header"
            InvalidCreds:
              value:
                code: 8 
                msg: "Invalid creds"

  schemas:
    ApiResponseCode:
      type: integer
      oneOf:
      - title: CodeSuccess
        const: 0 
        description: Successful operation
      - title: CodeUserAlreadyRegistered
        const: 1
      - title: CodeUsernameTaken
        const: 2
        description: Tried to register username that is already taken. 
      - title: CodeUsernameFormatNotValid
        const: 3 
        description: Invalid format for username
      - title: CodeReceiverDoesNotExist
        const: 4 
        description: Message recipient account doesn't exist
        deprecated: true
      - title: CodeEmailProfileAuthInvariantBroken
        const: 5 
        deprecated: true
      - title: CodeCantCreateAuthUser
        const: 6 
        description: Error in the auth provider
      - title: CodeUserNotRegistered
        const: 7 
        description: Referenced user doesn't exitst
      - title: CodeNotAuthenticated
        const: 8 
        description: User is not properly authenticated
      - title: CodeMaximumTokensNumberReached
        const: 9 
        description: User has registered too much devices for notifications(FCM)
      - title: CodeDeviceNameTooLong
        const: 10 
        description: Device name is too long
      - title: CodeInvalidArgs
        const: 11 
        description: Invalid API input(missing parameters or fields are in invalid format, etc.)
      
    ApiResponse:
      type: object
      additionalProperties: false
      properties:
        obj:
          oneOf:
            - $ref: '#/components/schemas/ObjType'
            - $ref: '#/components/schemas/MessageArray'
            - $ref: '#/components/schemas/DialogsConvIDArray'
            - $ref: '#/components/schemas/UserData'
          type: object
          default: null
        msg:
          type: string
        code:
          $ref: '#/components/schemas/ApiResponseCode'
    ObjType: 
      type: object
      default: null
    DialogsConvIDArray:
      type: array
      items:
        $ref: '#/components/schemas/ConvIDType'
    MessageArray:
      type: array
      items:
        $ref: '#/components/schemas/MessageData'

    MessageData:
      type: object
      properties:
        msg_id:
          type: string
          description: "Unique message id"
        to:
          $ref: '#/components/schemas/UidType'
        from:
          $ref: '#/components/schemas/UidType'
        msg:
          type: string
        created_at:
          description: "Message added to db timestamp"
          $ref: '#/components/schemas/TimestampType'

        conv_id:
          $ref: '#/components/schemas/ConvIDType'

    RegisterParams:
      type: object
      additionalProperties: false
      properties:
        username:
          $ref: '#/components/schemas/UsernameType'
        email:
          $ref: '#/components/schemas/EmailType'
        pwd:
          $ref: '#/components/schemas/PasswordType'
    TokenRegisterParams:
      type: object
      additionalProperties: false
      properties:
        token:
          $ref: '#/components/schemas/TokenType'
        device_name:
          $ref: '#/components/schemas/DeviceNameType'

    
    UsernameType:
      type: string
      minLength: 4
      maxLength: 32
    EmailType:
      type: string
      format: email
      maxLength: 254
    PasswordType:
      type: string
      format: password
      minLength: 6
      maxLength: 64
    UidType:
      type: string
      minLength: 10
      maxLength: 256
    ConvIDType:
      type: string
      minLength: 20
      maxLength: 512
      description: "Serves to uniquely identify the dialog between 2 users, got by concatenating both users UIDs in a sorted order"
    TokenType:
      description: "Device token"
      type: string
      minLength: 1
      maxLength: 2049
    DeviceNameType:
      description: "Device name"
      type: string
      minLength: 1
      maxLength: 2049 
    BoolType:
      type: boolean
    TimestampType:
      type: integer
      format: int64
    UserData:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        img_url:
          type: string
        tokens:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TokenType'
        contacts:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/BoolType'
      
    
  requestBodies:
    RegisterParams:
      description: "Regitration request parameters"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RegisterParams'
    TokenRegisterParams:
      description: "Required information to register token, enabling to send push notifications for the corresponding device"
      content:
        application/json:
          schema: '#/components/schemas/'
